### PR TITLE
Ex2

### PR DESCRIPTION
**Pull request by natiohayun**
Ex2 - Netanel Ohayun 036507895

### CODE REVIEW

**Comment by robi-y** [comment]
Some comments:
- Actor table: I would look for a more concrete name than 'user', this can also help focus on the actor goals. Some of the goals are a little too low level, e.g., a user usually don't see login as a goal - maybe security is a goal (of who?)
- UC diagram: missing system boundry, I think the relations between usecases should be reversed, e.g. checkout includes adding items. Not clear the role of the 'user' actor
-  use case: missing main flow and alterntives

**Comment by robi-y** [comment]
also missing use case xmi file

**Comment by natiohayun** [comment]
We talked last week and you said that for the ex i dont have to sub

**Comment by natiohayun** [comment]
Hi roby
we talk about the system boundary and last week i explained that the first tool that i used isnt support it and you said its ok also at work we are using in the term of user in all the use cases
so please if you can fix the grade

**Comment by robi-y** [comment]
done

**Comment by natiohayun** [comment]
the grase is the same 
dont i get extra point  ? :)

**Comment by robi-y** [comment]
Haven't published grades in recent days...

**Pull request closed without merging**
