### PR TITLE
ex2 part 1

### PR DESCRIPTION
**Pull request by katyadenef**
Hi,

We have 3 files here: 1 md, 1 xmi and 1 picture.
By Katya Denef, Ran Itzhaky, Itzik Rabinovich.

BR,
Katya.

### CODE REVIEW

**Comment by robi-y** [comment]
I'm not sure "new customer" should be a different actor (after all everybody is new sometimes), this also revealed in the actor table - registration is not usually a goal for a customer (maybe security).
Nice detailed use case - I think it mixes a bit levels and it id not totally clear what is the system role in the main scenario

**Comment by katyadenef** [comment]
We actually think that a new (i.e., unregistered) customer is a different actor, since they clearly have less potential use-cases. Such a customer's goal can be to register, since this allows them to carry out purchases and maybe gives some discount (if we assume an unregistered customer has a way of buying things online as well).
Could you please give some examples of mixing levels in a use-case?

BR,
Katya (on behalf of Ran and Itzik as well).

**Comment by katyadenef** [comment]
Hi.

Following our conversation, I think we deserve a higher grade than 95.

BR,
Katya.

**Comment by robi-y** [comment]
:+1: :smile:

**Pull request closed without merging**
